version: '3.1'

services:

  server:
    environment:
      MYSQL_HOST: mysql
      MYSQL_PASSWORD: $$MYSQL_ROOT_PASSWORD
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql
      - rabbitmq
    ports:
      - "8090:8090"

  mysql:
    container_name: gitbank_mysql
    image: mysql:8.0.27
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
    ports:
      - "3306:3306"

  rabbitmq:
    image: rabbitmq:management-alpine
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  mysql_data:
    name: gitbank_mysql_data


networks:
  default:
    name: gitbank_network